swagger: '2.0'
info: 
  title: BIC
  description: |
    API for managing BIC codes associated to a customer
  version: ""
host: 'services.ird.govt.nz:4046'
basePath: /gateway/bic/
schemes: 
  - https
paths: 
  /bic: 
    post: 
      tags: 
        - Update or add BIC code
      summary: Update or add BIC code
      description: Adds new or updates existing BIC code to customer
      operationId: bicPOST
      consumes: 
        - 'application/json; charset=utf-8'
      produces: 
        - 'application/json; charset=utf-8'
      parameters: 
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/bic_POST_Request'
      responses: 
        '400': 
          description: 'HttpStatus: 400 - BadRequest'
          schema: 
            $ref: '#/definitions/bic_POST_Response400'
        '500': 
          description: 'HttpStatus: 500 - InternalServerError'
          schema: 
            $ref: '#/definitions/bic_POST_Response500'
        default: 
          description: ' '
          schema: 
            $ref: '#/definitions/bic_POST_ResponseDefault'
    delete: 
      tags: 
        - Cease BIC code
      summary: Cease BIC code
      description: Ceases an existing BIC code on a customer
      operationId: bicDELETE
      consumes: 
        - 'application/json; charset=utf-8'
      produces: 
        - 'application/json; charset=utf-8'
      parameters: 
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/bic_DELETE_Request'
      responses: 
        '400': 
          description: 'HttpStatus: 400 - BadRequest'
          schema: 
            $ref: '#/definitions/bic_DELETE_Response400'
        '500': 
          description: 'HttpStatus: 500 - InternalServerError'
          schema: 
            $ref: '#/definitions/bic_DELETE_Response500'
        default: 
          description: ' '
          schema: 
            $ref: '#/definitions/bic_DELETE_ResponseDefault'
  /status: 
    get: 
      tags: 
        - Web Service Status
      summary: Web Service Status
      description: 'This web service sends a 200 HTTP response with a message body of "OK".'
      operationId: statusGET
      parameters: []
      responses: 
        default: 
          description: ' '
definitions: 
  bic_POST_Request: 
    type: object
    required: 
      - CustomerID
      - CustomerIDType
      - BICCode
    properties: 
      CustomerID: 
        type: string
        description: '<p>The unique identifier of a customer.</p>'
        maxLength: 10
        minLength: 9
      CustomerIDType: 
        type: string
        description: '<p>The type of unique identifier of a customer.</p><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>IRD</td><td>IRD number</td></tr><tr><td>CST</td><td>Customer Identifier</td></tr><tr><td></td><td></td></tr></tbody></table>'
        maxLength: 3
        minLength: 3
        enum: 
          - IRD
          - CST
          - ""
      BICCode: 
        type: string
        description: '<p>Business Industry Classification code is a way of classifying a self-employed person or business by their main service or product.</p>'
        maxLength: 8
        minLength: 6
      Commence: 
        type: string
        format: date
        description: '<p>Activity code''s commence date. Indicates when this activity began.</p>'
        maxLength: 10
  bic_DELETE_Request: 
    type: object
    required: 
      - CustomerID
      - CustomerIDType
      - BICCode
    properties: 
      CustomerID: 
        type: string
        description: '<p>The unique identifier of a customer.</p>'
        maxLength: 10
        minLength: 9
      CustomerIDType: 
        type: string
        description: '<p>The type of unique identifier of a customer.</p><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>IRD</td><td>IRD number</td></tr><tr><td>CST</td><td>Customer Identifier</td></tr><tr><td></td><td></td></tr></tbody></table>'
        maxLength: 3
        minLength: 3
        enum: 
          - IRD
          - CST
          - ""
      BICCode: 
        type: string
        description: '<p>Business Industry Classification code is a way of classifying a self-employed person or business by their main service or product.</p>'
        maxLength: 8
        minLength: 6
      Cease: 
        type: string
        format: date
        description: '<p>Activity code''s cease date. Indicates when this activity ceased.</p>'
        maxLength: 10
  bic_POST_Response400: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>BIC000</td><td>Processing of request failed despite request being valid, try again later</td></tr><tr><td>BIC102</td><td>Activity commence date may not be in the future</td></tr><tr><td>CST404</td><td>A record could not be located for the given identifier.</td></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr><tr><td>EV2234</td><td>IR number failed check digit</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - BIC000
                - BIC102
                - CST404
                - EV1020
                - EV1021
                - EV1100
                - EV2234
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  bic_POST_Response500: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EU6001</td><td>Unexpected error occurred</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EU6001
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - server
            message: 
              type: string
              description: Error Message
  bic_POST_ResponseDefault: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>BIC000</td><td>Processing of request failed despite request being valid, try again later</td></tr><tr><td>BIC102</td><td>Activity commence date may not be in the future</td></tr><tr><td>CST404</td><td>A record could not be located for the given identifier.</td></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr><tr><td>EV2234</td><td>IR number failed check digit</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - BIC000
                - BIC102
                - CST404
                - EV1020
                - EV1021
                - EV1100
                - EV2234
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  bic_DELETE_Response400: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>BIC101</td><td>Unable to find activity code provided on the customer</td></tr><tr><td>BIC103</td><td>Activity cease date may not be in the future</td></tr><tr><td>CST404</td><td>A record could not be located for the given identifier.</td></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr><tr><td>EV2234</td><td>IR number failed check digit</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - BIC101
                - BIC103
                - CST404
                - EV1020
                - EV1021
                - EV1100
                - EV2234
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - security
                - validation
            message: 
              type: string
              description: Error Message
  bic_DELETE_Response500: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EU6001</td><td>Unexpected error occurred</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EU6001
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - server
            message: 
              type: string
              description: Error Message
  bic_DELETE_ResponseDefault: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>BIC101</td><td>Unable to find activity code provided on the customer</td></tr><tr><td>BIC103</td><td>Activity cease date may not be in the future</td></tr><tr><td>CST404</td><td>A record could not be located for the given identifier.</td></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr><tr><td>EV2234</td><td>IR number failed check digit</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - BIC101
                - BIC103
                - CST404
                - EV1020
                - EV1021
                - EV1100
                - EV2234
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - security
                - validation
            message: 
              type: string
              description: Error Message