swagger: '2.0'
info: 
  title: Notifications
  description: A REST API Service that enables actionable event notifications to be retrieved by external software platforms.
  version: "20230331"
host: services.ird.govt.nz:4046
basePath: /gateway/notification/
schemes: 
  - https
paths: 
  /list: 
    post: 
      tags: 
        - Notification service
      summary: Notification service
      description: 'The notification service allows for retrieval of actionable events. Notifications are very lean and contain no data. The purpose of the notification is to be delivered to software instead of displayed to end-users. It is the responsibility of the software to prioritise, filter and decide when and how to respond to each notification using the data within it.'
      operationId: listPOST
      consumes: 
        - 'application/json; charset=utf-8'
      produces: 
        - 'application/json; charset=utf-8'
      parameters: 
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/list_POST_Request'
      responses: 
        '200': 
          description: 'HttpStatus: 200 - OK'
          schema: 
            $ref: '#/definitions/list_POST_Response200'
        '400': 
          description: 'HttpStatus: 400 - BadRequest'
          schema: 
            $ref: '#/definitions/list_POST_Response400'
        '500': 
          description: 'HttpStatus: 500 - InternalServerError'
          schema: 
            $ref: '#/definitions/list_POST_Response500'
        default: 
          description: ' '
          schema: 
            $ref: '#/definitions/list_POST_ResponseDefault'
  /status: 
    get: 
      tags: 
        - Web Service Status
      summary: Web Service Status
      description: 'This web service sends a 200 HTTP response with a message body of "OK".'
      operationId: statusGET
      parameters: []
      responses: 
        default: 
          description: ' '
definitions: 
  list_POST_Request: 
    type: object
    required: 
      - FromDateTime
    properties: 
      QueryIDType: 
        type: string
        description: '<p>The QueryIDType is the type of ID that is used to filter notifications. This field name is case sensitive.</p><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>CLTLID</td><td>Other Tax Preparer Client List Identifier</td></tr><tr><td>CST</td><td>A non-IRD Number type identifier. Given to customers who do not have an IRD number in the system</td></tr><tr><td>IRD</td><td>Inland Revenue Department ID</td></tr><tr><td>KSF</td><td>KiwiSaver Schemes ID</td></tr><tr><td>LSTID</td><td>Tax Agent List Identifier</td></tr></tbody></table>'
        maxLength: 6
        minLength: 1
        enum: 
          - CLTLID
          - CST
          - IRD
          - KSF
          - LSTID
      QueryID: 
        type: string
        description: '<p>The QueryID is used to filter available notifications by recipient. This field name is case sensitive.</p>'
        maxLength: 30
      FromDateTime: 
        type: string
        format: 'date-time'
        description: '<p>The earliest point in time on which to select notifications based on their date-time stamp. Must not be a future date. This is an ISO8601 formatted datetime. This field name is case sensitive. Example: 2020-01-02T08:06:26</p>'
      ToDateTime: 
        type: string
        format: 'date-time'
        description: '<p>The latest point in time on which to select notifications based on their date-time stamp. Must not be a future date. This is an ISO8601 formatted date time. Example: 2020-01-15T15:53:00</p>'
  list_POST_Response200: 
    type: object
    required: 
      - Notifications
    properties: 
      Notifications: 
        type: array
        description: '<p>Notifications response array</p>'
        items: 
          type: object
          description: '<p>Notification object</p>'
          required: 
            - NotificationKey
            - RecordCreated
            - EventDate
            - Category
            - SubCategory
            - Type
            - Description
            - DocumentID
            - DocumentLocationID
            - ExtID
            - ExtIDType
            - IDType
            - ID
            - SubjectIDType
            - SubjectID
            - FilingPeriod
            - DueDate
          properties: 
            NotificationKey: 
              type: number
              format: int64
              description: '<p>Unique notification identifier</p>'
            RecordCreated: 
              type: string
              description: '<p>Point in time the notification object was created. This is an ISO8601 formatted datetime. Example: 2020-01-01T06:12:15</p>'
            EventDate: 
              type: string
              description: '<p>Date time corresponding to event that created this notification. This is an ISO8601 formatted datetime. Example: 2020-01-01T08:06:26</p>'
            Category: 
              type: string
              description: '<p>Notification category</p><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>1</td><td>Event notifications</td></tr><tr><td>2</td><td>Reminder notifications</td></tr><tr><td>3</td><td>Request for information notifications</td></tr><tr><td>4</td><td>Error notifications</td></tr><tr><td>5</td><td>Action required notifications</td></tr></tbody></table>'
              maxLength: 1
              minLength: 1
              enum: 
                - '1'
                - '2'
                - '3'
                - '4'
                - '5'
            SubCategory: 
              type: string
              description: '<p>Notification sub category.  New notification sub categories can be added at any time.</p><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>Compliance</td><td>Compliance notifications related to a case, audit, or collection</td></tr><tr><td>Customer</td><td>Notifications related to registration or that fit within the customer data model</td></tr><tr><td>Employer</td><td>Employer notifications for PAYE, employee relationship, or employment data correction</td></tr><tr><td>GST</td><td>Notifications related to Goods and Services Tax</td></tr><tr><td>IncomeTax</td><td>Notifications related to income tax</td></tr><tr><td>KiwiSaver</td><td>KiwiSaver notifications</td></tr><tr><td>PIE</td><td>Portfolio investment entities</td></tr><tr><td>Refund</td><td>Refund event</td></tr><tr><td>Return</td><td>Return event or data corrective notifications</td></tr></tbody></table>'
              maxLength: 30
              minLength: 1
              enum: 
                - Compliance
                - Customer
                - Employer
                - GST
                - IncomeTax
                - KiwiSaver
                - PIE
                - Refund
                - Return
            Type: 
              type: string
              description: '<p>Notification type.  New notification types can be added at any time.</p><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>ACCCLS</td><td>Account cease date has changed</td></tr><tr><td>ACCDLK</td><td>An account has had a link removed or ceased for a business intermediary</td></tr><tr><td>ACCLNK</td><td>An account has been linked to a business intermediary</td></tr><tr><td>ACCREG</td><td>A new account has been registered</td></tr><tr><td>ACTBAS</td><td>Accounting basis has changed</td></tr><tr><td>ANRCHG</td><td>Agent non-resident insurer has changed</td></tr><tr><td>BALDAT</td><td>Balance date has changed</td></tr><tr><td>CNGADD</td><td>A consolidated group indicator has been added</td></tr><tr><td>CNGRMV</td><td>A consolidated group indicator has been removed</td></tr><tr><td>CNMADD</td><td>A consolidated group member indicator has been added</td></tr><tr><td>CNMRMV</td><td>A consolidated group member indicator has been removed</td></tr><tr><td>COLCAS</td><td>Information has been requested to progress a collection case</td></tr><tr><td>COMSTS</td><td>There has been a change to a company''s active/non-active status.</td></tr><tr><td>CSTSUB</td><td>A customer sub-type attribute has changed</td></tr><tr><td>DISPEN</td><td>A refund is pending and requires an updated bank account</td></tr><tr><td>DTCINF</td><td>A donation tax credit application requires more information</td></tr><tr><td>EOTCHG</td><td>Extension of time has changed</td></tr><tr><td>FILFRQ</td><td>Filing frequency has changed</td></tr><tr><td>ICAADD</td><td>An imputation group (ICA) indicator has been added</td></tr><tr><td>ICARMV</td><td>An imputation group (ICA) indicator has been removed</td></tr><tr><td>IMGADD</td><td>An imputation group member indicator has been added</td></tr><tr><td>IMGRMV</td><td>An imputation group member indicator has been removed</td></tr><tr><td>INCFNR</td><td>An IR4J/8J has not been received</td></tr><tr><td>INCGRP</td><td>Individual group indicator has changed</td></tr><tr><td>INCWFT</td><td>WfFTC is waiting for an Income tax assessment</td></tr><tr><td>KSSDED</td><td>Employee''s savings suspension has ceased restart employee deductions.</td></tr><tr><td>KSSS1</td><td>Employee has started KiwiSaver</td></tr><tr><td>KSSS2</td><td>Employer has not started the employee on KiwiSaver since receiving the first request</td></tr><tr><td>LTCADD</td><td>A look through company indicator has been added</td></tr><tr><td>LTCRMV</td><td>A look through company indicator has been removed</td></tr><tr><td>MAOADD</td><td>A Māori authority indicator has been added</td></tr><tr><td>MAORMV</td><td>A Māori authority indicator has been removed</td></tr><tr><td>NEWMAL</td><td>You have new mail</td></tr><tr><td>PIR</td><td>A portfolio investment payee has been detected as using the wrong prescribed investor rate (PIR)</td></tr><tr><td>PRVASM</td><td>A provisional tax assessment has changed</td></tr><tr><td>PRVMTD</td><td>Provisional tax method has changed</td></tr><tr><td>QCIRMV</td><td>A qualifying company indicator has been removed</td></tr><tr><td>RTNAVL</td><td>A return is now available to be filed</td></tr><tr><td>RTNCMP</td><td>Assessment has finished processing</td></tr><tr><td>RTNDAS</td><td>A new default assessment has been added</td></tr><tr><td>RTNDUE</td><td>A return is now overdue</td></tr><tr><td>RTNINN</td><td>An automatic income tax assessment requires more information to finalise</td></tr><tr><td>RTNPRC</td><td>Information has been requested to progess an assessment correction</td></tr><tr><td>TAXCDE</td><td>An employee has been detected as using an incorrect tax code</td></tr><tr><td>TRNTAS</td><td>Trans Tasman has changed</td></tr><tr><td>TXPADD</td><td>A tax pooling indicator has been added</td></tr><tr><td>TXPRMV</td><td>A tax pooling indicator has been removed</td></tr></tbody></table>'
              maxLength: 30
              minLength: 1
              enum: 
                - ACCCLS
                - ACCDLK
                - ACCLNK
                - ACCREG
                - ACTBAS
                - ANRCHG
                - BALDAT
                - CNGADD
                - CNGRMV
                - CNMADD
                - CNMRMV
                - COLCAS
                - COMSTS
                - CSTSUB
                - DISPEN
                - DTCINF
                - EOTCHG
                - FILFRQ
                - ICAADD
                - ICARMV
                - IMGADD
                - IMGRMV
                - INCFNR
                - INCGRP
                - INCWFT
                - KSSDED
                - KSSS1
                - KSSS2
                - LTCADD
                - LTCRMV
                - MAOADD
                - MAORMV
                - NEWMAL
                - PIR
                - PRVASM
                - PRVMTD
                - QCIRMV
                - RTNAVL
                - RTNCMP
                - RTNDAS
                - RTNDUE
                - RTNINN
                - RTNPRC
                - TAXCDE
                - TRNTAS
                - TXPADD
                - TXPRMV
            Description: 
              type: string
              description: '<p>Notification description</p>'
              maxLength: 255
              minLength: 1
            DocumentID: 
              type: number
              format: int64
              description: '<p>The ID of a document that can be retreived through the document service.</p>'
            DocumentLocationID: 
              type: number
              format: int64
              description: '<p>An ID corresponding to the location where a document submitted through the document service will added.</p>'
            ExtID: 
              type: string
              description: '<p>An external ID for providing more information with a notification</p>'
              maxLength: 30
            ExtIDType: 
              type: string
              description: '<p>Type of external ID, if one is provided</p>'
              maxLength: 30
            IDType: 
              type: string
              description: '<p>The type of ID for the recipient of the notification</p>'
              maxLength: 6
              minLength: 1
            ID: 
              type: string
              description: '<p>An ID for the main recipient of the notification. This can be filtered with a query ID and query ID type.</p>'
              maxLength: 30
              minLength: 1
            SubjectIDType: 
              type: string
              description: '<p>Subject ID Type.  Example: Recipient of notification is employer, the subject ID could be that of an employee.</p>'
              maxLength: 30
            SubjectID: 
              type: string
              description: '<p>Subject ID.  Example: Recipient of notification is employer, the subject ID could be that of an employee.</p>'
              maxLength: 30
            FilingPeriod: 
              type: string
              description: '<p>Filing period. This is an ISO8601 formatted date. Example: 2020-03-31. If not applicable, will be returned as ''9999-12-31''</p>'
            DueDate: 
              type: string
              description: '<p>Due date. This is an ISO8601 formatted date. Example: 2020-03-31. If not applicable, will be returned as ''9999-12-31''</p>'
  list_POST_Response400: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1022</td><td>Access is not permitted for the requester to perform this operation for the submitted identifier</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr><tr><td>EV2302</td><td>The To date field cannot be before the From date field</td></tr><tr><td>KS0113</td><td>Future dated field. This field must be today or in the past.</td></tr><tr><td>NOT001</td><td>The number of notifications retrieved exceeds the maximum limit of notifications.  Please filter your criteria.</td></tr><tr><td>NOT002</td><td>A query ID and query ID type are required.</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EV1020
                - EV1021
                - EV1022
                - EV1100
                - EV2302
                - KS0113
                - NOT001
                - NOT002
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  list_POST_Response500: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EU6001</td><td>Unexpected error occurred</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EU6001
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  list_POST_ResponseDefault: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1022</td><td>Access is not permitted for the requester to perform this operation for the submitted identifier</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr><tr><td>EV2302</td><td>The To date field cannot be before the From date field</td></tr><tr><td>KS0113</td><td>Future dated field. This field must be today or in the past.</td></tr><tr><td>NOT001</td><td>The number of notifications retrieved exceeds the maximum limit of notifications.  Please filter your criteria.</td></tr><tr><td>NOT002</td><td>A query ID and query ID type are required.</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EV1020
                - EV1021
                - EV1022
                - EV1100
                - EV2302
                - KS0113
                - NOT001
                - NOT002
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message